"use client";

import { useCallback, useEffect, useState } from "react";
import { BookOpenCheck, FileQuestion, Layers3, ListChecks, Network, RefreshCw, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { KNOWLEDGE_GENERATION_LABELS } from "@/features/knowledge/constants/knowledge.config";
import type { KnowledgeArtifactRecord, KnowledgeArtifactType } from "@/features/knowledge/types/knowledge";
import { LearningArtifactContent } from "./learning-artifacts";

const ARTIFACTS: { type: KnowledgeArtifactType; icon: typeof Sparkles; description: string; empty: string }[] = [
  { type: "SUMMARY", icon: Sparkles, description: "A structured overview of the book’s ideas.", empty: "Get a concise, grounded reading guide for this book." },
  { type: "TAKEAWAYS", icon: ListChecks, description: "Key learning points worth remembering.", empty: "Turn the book’s central ideas into scannable learning cards." },
  { type: "FLASHCARDS", icon: Layers3, description: "Active recall cards for confident study.", empty: "Turn this book into active recall cards." },
  { type: "QUIZ", icon: FileQuestion, description: "Practice questions with explanations.", empty: "Check your understanding with grounded practice questions." },
  { type: "MIND_MAP", icon: Network, description: "An expandable map of connected concepts.", empty: "Explore how the book’s core ideas connect." },
];

export function KnowledgeWorkspace({ slug, disabled }: { slug: string; disabled: boolean }) {
  const [artifacts, setArtifacts] = useState<KnowledgeArtifactRecord[]>([]);
  const [activeType, setActiveType] = useState<KnowledgeArtifactType>("SUMMARY");
  const [error, setError] = useState<string>();
  const [pollingStopped, setPollingStopped] = useState(false);
  const load = useCallback(async (manual = false) => {
    try {
      const response = await fetch(`/api/books/${encodeURIComponent(slug)}/knowledge`);
      if (!response.ok) throw new KnowledgeLoadError(response.status);
      const body: { artifacts: KnowledgeArtifactRecord[] } = await response.json();
      setArtifacts(body.artifacts); setError(undefined); if (manual) setPollingStopped(false);
    } catch (reason) { setPollingStopped(true); setError(reason instanceof KnowledgeLoadError && reason.status === 404 ? "This book is unavailable, so learning materials cannot be refreshed." : "Unable to refresh learning materials. Please try again."); }
  }, [slug]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (pollingStopped || !artifacts.some((artifact) => artifact.status === "REQUESTED" || artifact.status === "GENERATING")) return; const timer = window.setInterval(() => void load(), 2_500); return () => window.clearInterval(timer); }, [artifacts, load, pollingStopped]);
  const generate = async (type: KnowledgeArtifactType) => { try { const response = await fetch(`/api/books/${encodeURIComponent(slug)}/knowledge`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type }) }); if (!response.ok) throw new Error(); const body: { artifact: KnowledgeArtifactRecord } = await response.json(); setArtifacts((current) => [...current.filter((artifact) => artifact.type !== type), body.artifact]); setPollingStopped(false); setError(undefined); } catch { setError("Unable to start generation. Please try again."); } };
  const item = ARTIFACTS.find((candidate) => candidate.type === activeType)!;
  const artifact = artifacts.find((candidate) => candidate.type === activeType);
  return <section aria-labelledby="knowledge-heading" className="border-border bg-card overflow-hidden rounded-2xl border shadow-sm"><header className="border-border border-b px-5 py-6 sm:px-7"><div className="flex items-start gap-3"><div className="bg-primary/10 text-primary rounded-xl p-2.5"><BookOpenCheck className="size-5" /></div><div><p className="text-primary text-sm font-semibold">Knowledge workspace</p><h2 id="knowledge-heading" className="mt-1 text-2xl font-bold tracking-tight">Learn from this book</h2><p className="text-muted-foreground mt-2 max-w-2xl text-sm leading-6">Create focused study materials grounded in your uploaded book.</p></div></div></header>{error ? <div role="alert" className="bg-destructive/10 text-destructive border-destructive/20 flex flex-wrap items-center justify-between gap-3 border-b px-5 py-3 text-sm sm:px-7"><span>{error}</span><Button type="button" size="sm" variant="outline" onClick={() => void load(true)}>Retry</Button></div> : null}<div role="tablist" aria-label="Knowledge materials" className="border-border flex gap-1 overflow-x-auto border-b p-2">{ARTIFACTS.map((tab) => <KnowledgeTab key={tab.type} item={tab} active={activeType === tab.type} status={artifacts.find((artifact) => artifact.type === tab.type)?.status} onSelect={() => setActiveType(tab.type)} />)}</div><div role="tabpanel" className="p-5 sm:p-7"><ArtifactPanel item={item} artifact={artifact} disabled={disabled} onGenerate={generate} /></div></section>;
}

function KnowledgeTab({ item, active, status, onSelect }: { item: (typeof ARTIFACTS)[number]; active: boolean; status?: KnowledgeArtifactRecord["status"]; onSelect: () => void }) { const Icon = item.icon; return <button type="button" role="tab" aria-selected={active} onClick={onSelect} className={`focus-visible:ring-ring/30 flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium transition-colors focus-visible:ring-4 ${active ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><Icon className="size-4" />{KNOWLEDGE_GENERATION_LABELS[item.type]}{status === "GENERATING" || status === "REQUESTED" ? <span className="bg-primary-foreground/20 size-1.5 rounded-full" aria-label="Generating" /> : null}</button>; }
function ArtifactPanel({ item, artifact, disabled, onGenerate }: { item: (typeof ARTIFACTS)[number]; artifact?: KnowledgeArtifactRecord; disabled: boolean; onGenerate: (type: KnowledgeArtifactType) => Promise<void> }) { const Icon = item.icon; const active = artifact?.status === "REQUESTED" || artifact?.status === "GENERATING"; return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Icon className="text-primary size-5" /><h3 className="text-xl font-bold">{KNOWLEDGE_GENERATION_LABELS[item.type]}</h3></div><p className="text-muted-foreground mt-2 text-sm leading-6">{item.description}</p></div>{artifact?.status === "COMPLETED" ? <span className="bg-primary/10 text-primary rounded-full px-3 py-1 text-xs font-semibold">Ready to study</span> : null}</div>{active ? <GenerationState artifact={artifact} /> : null}{artifact?.status === "FAILED" ? <FailureState artifact={artifact} onGenerate={() => onGenerate(item.type)} /> : null}{artifact?.status === "COMPLETED" ? <LearningArtifactContent artifact={artifact} /> : null}{!artifact ? <EmptyState item={item} disabled={disabled} onGenerate={() => onGenerate(item.type)} /> : null}{artifact?.status === "COMPLETED" ? <Button type="button" variant="outline" className="mt-7" onClick={() => void onGenerate(item.type)}><RefreshCw />Regenerate</Button> : null}</div>; }
function GenerationState({ artifact }: { artifact: KnowledgeArtifactRecord }) { const detail = generationDetail(artifact); return <div className="bg-muted/60 mt-7 rounded-2xl p-5"><div className="flex items-center justify-between gap-4"><div><p className="font-semibold">Creating your learning materials</p><p className="text-muted-foreground mt-1 text-sm">{detail.title}</p>{detail.batch ? <p className="text-muted-foreground mt-1 text-xs">{detail.batch}</p> : null}</div><span className="text-primary text-sm font-bold">{artifact.progress}%</span></div><div className="bg-background mt-4 h-2 overflow-hidden rounded-full"><div className="bg-primary h-full rounded-full transition-all" style={{ width: `${artifact.progress}%` }} /></div><ol className="text-muted-foreground mt-5 grid gap-2 text-sm sm:grid-cols-3"><li>{artifact.progress >= 10 ? "✓" : "○"} Loading book content</li><li>{artifact.progress >= 30 ? "✓" : "○"} Preparing batches</li><li>{artifact.progress >= 50 ? "⏳" : "○"} Generating {KNOWLEDGE_GENERATION_LABELS[artifact.type].toLowerCase()}</li></ol></div>; }
function generationDetail(artifact: KnowledgeArtifactRecord): { title: string; batch?: string } { if (artifact.generationStage === "LOADING_SEGMENTS") return { title: "Analyzing book content" }; if (artifact.generationStage === "PREPARING_BATCHES") return { title: "Preparing generation batches", batch: batchText(artifact) }; if (artifact.generationStage === "GENERATING_CONTENT") return { title: generationContentLabel(artifact.type), batch: batchText(artifact, "Generating") }; if (artifact.generationStage === "VALIDATING") return { title: "Validating learning material" }; if (artifact.generationStage === "SAVING") return { title: "Saving results" }; return { title: "Starting generation" }; }
function batchText(artifact: KnowledgeArtifactRecord, prefix = "Batch"): string | undefined { return artifact.currentBatch && artifact.totalBatches ? `${prefix} batch ${artifact.currentBatch} of ${artifact.totalBatches}`.replace("Batch batch", "Batch") : undefined; }
function generationContentLabel(type: KnowledgeArtifactType): string { if (type === "FLASHCARDS") return "Creating flashcards"; if (type === "QUIZ") return "Preparing questions and explanations"; if (type === "MIND_MAP") return "Structuring concepts"; return "Generating AI content"; }
function EmptyState({ item, disabled, onGenerate }: { item: (typeof ARTIFACTS)[number]; disabled: boolean; onGenerate: () => Promise<void> }) { const Icon = item.icon; return <div className="border-border bg-muted/30 mt-7 rounded-2xl border border-dashed p-8 text-center"><div className="bg-primary/10 text-primary mx-auto flex size-11 items-center justify-center rounded-xl"><Icon className="size-5" /></div><h4 className="mt-4 font-semibold">No {KNOWLEDGE_GENERATION_LABELS[item.type].toLowerCase()} yet</h4><p className="text-muted-foreground mx-auto mt-2 max-w-md text-sm leading-6">{item.empty}</p><Button type="button" className="mt-5" disabled={disabled} onClick={() => void onGenerate()}><Sparkles />Generate {KNOWLEDGE_GENERATION_LABELS[item.type]}</Button></div>; }
function FailureState({ artifact, onGenerate }: { artifact: KnowledgeArtifactRecord; onGenerate: () => Promise<void> }) { return <div className="border-destructive/20 bg-destructive/5 mt-7 rounded-2xl border p-5"><p className="font-semibold">{generationDetail(artifact).title} failed</p><p className="text-muted-foreground mt-1 text-sm">{artifact.errorMessage ?? "Generation temporarily unavailable. Try again in a few moments."}</p><Button type="button" variant="outline" className="mt-4" onClick={() => void onGenerate()}><RefreshCw />Try again</Button></div>; }
class KnowledgeLoadError extends Error { public constructor(public readonly status: number) { super(); } }
